name: Post to Instagram

on:
  schedule:
    - cron: '0 * * * *'  # every 1 hour
  workflow_dispatch:        # manual trigger from GitHub UI

jobs:
  post:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download fonts
        run: python setup.py

      - name: Run pipeline
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINISECRET }}
          GROQ_API_KEY: ${{ secrets.GROKSECRET }}
          INSTAGRAM_USERNAME: ${{ secrets.INSTAUSERNAMESECRET }}
          INSTAGRAM_PASSWORD: ${{ secrets.INSTAPASSWORDSECRET }}
          NEWS_TOPIC: "entertainment,sports,technology,world news,science,business,health,politics,space,AI,gaming,environment"
          POST_COUNT: "2"
          POST_INTERVAL_HOURS: "12"
          IG_USER_ID: ${{ secrets.IGUSERIDSECRET }}
          IG_ACCESS_TOKEN: ${{ secrets.IGACCESSTOKENSECRET }}
          IG_APP_SECRET: ${{ secrets.IGAPPSECRET }}
          IMGBB_API_KEY: ${{ secrets.IMGBBKEYSECRET }}
        run: python main.py --once
